version: 2

models:
  - name: inter_discounts_cleaned_data
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: items_id
        tests:
          - not_null
      - name: discount_price
          - not_null
      - name: original_price
      - name: percentage
      - name: created_at
        tests:
          - not_null
  - name: inter_items_cleaned_data
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: sku
        tests:
          - not_null
      - name: name
        tests:
          - not_null
      - name: source
        tests:
          - not_null
          - dbt_utils.not_empty_string
      - name: created_at
        tests:
          - not_null
      - name: category_trimmed
        tests:
          - not_null
      - name: category_fix
        tests:
          - not_null