version: 2

models:
  - name: stg_discounts
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: items_id
        tests:
          - not_null
      - name: discount_price
      - name: original_price
      - name: percentage
      - name: description
      - name: created_at
        tests:
          - not_null
  - name: stg_items
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: sku
        tests:
          - not_null
      - name: name
        tests:
          - not_null
      - name: category
        tests:
          - not_null
      - name: image
        tests:
          - not_null
      - name: link
        tests:
          - not_null
          - dbt_utils.not_empty_string
      - name: source
        tests:
          - not_null
          - dbt_utils.not_empty_string
      - name: created_at
        tests:
          - not_null