version: 2

models:
  - name: mart_discounted_items
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: discount_price
          - not_null
      - name: percentage
      - name: created_at
        tests:
          - not_null
      - name: category_fix
        tests:
          - not_null
      - name: source
        tests:
          - not_null
      - name: name
        tests:
          - not_null
