indiemart_challenge:
  outputs:
    dev:
      dataset: sql_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /mnt/e/Dataflow_example-main/indiemart_challenge/active-complex-400513-cba49053a549.json
      location: US
      method: service-account
      priority: interactive
      project: active-complex-400513
      threads: 4
      type: bigquery
  target: dev